name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@main
            - run: node -v
            - name: Vuepress deploy
              uses: jenkey2011/vuepress-deploy@1.6.1
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BUILD_SCRIPT: yarn && yarn build
                  TARGET_BRANCH: gh-pages
                  BUILD_DIR: docs/.vuepress/dist
