name: Build and Deploy
on: [push]
jobs:
  node-update:
    - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '14'
  - run: yarn install
  build-and-deploy:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout
      uses: actions/checkout@main
 
    - name: Vuepress deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn build 
        TARGET_BRANCH: gh-pages
        BUILD_DIR: src/.vuepress/dist
