name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install -g
    - name: Vuepress deploy
      uses: jenkey2011/vuepress-deploy@1.0.1
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_SCRIPT: yarn && yarn install && yarn build 
        TARGET_BRANCH: gh-pages
        BUILD_DIR: src/.vuepress/dist
